In [127]:
import torch

# Intro

A tensor is like a multi-dimensional array (a generalization of a matrix). You can make a tensor from a list. This will be 1-dimensional tensor (similar to a vector).

In [128]:
my_list=[1,2,3, 4]

In [129]:
my_tensor= torch.Tensor(my_list)

In [130]:
my_tensor

tensor([1., 2., 3., 4.])

In [131]:
my_tensor[2]

tensor(3.)

Wanna convert it to a number? No problem at all!

In [132]:
my_tensor.numpy()

array([1., 2., 3., 4.], dtype=float32)

Wanna convert it back to a tensor? That's so easy!

In [133]:
torch.Tensor(my_tensor.numpy())

tensor([1., 2., 3., 4.])

Get it's shape

In [134]:
torch.Tensor(my_tensor.numpy()).shape

torch.Size([4])

# Making a Tensor from a Numpy Array

How about making a Tensor from a numpy array? Let's go!

In [135]:
import numpy as np

First, we make a Numpy array

In [136]:
my_np_array = np.array([[2, 4, 6, 8],[10, 12, 14, 16]])

Now we can get it's shape

In [137]:
my_np_array.shape

(2, 4)

In [138]:
my_np_array.dtype

dtype('int32')

In [139]:
my_tensor=torch.Tensor(my_np_array)

In [140]:
my_tensor

tensor([[ 2.,  4.,  6.,  8.],
        [10., 12., 14., 16.]])

In [141]:
my_tensor.shape

torch.Size([2, 4])

Another way of making a Tensor from a Numpy array...

In [142]:
my_tensor = torch.from_numpy(my_np_array)

In [143]:
my_tensor

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]], dtype=torch.int32)

In [144]:
my_tensor.shape

torch.Size([2, 4])

In [145]:
my_tensor.dtype

torch.int32

Even the shape can be converted to a number

In [146]:
my_tensor.shape[0]

2

# Making a Random Tensor

In [147]:
torch.rand((3,5))

tensor([[0.9666, 0.9889, 0.5134, 0.8328, 0.8373],
        [0.8905, 0.2216, 0.6570, 0.4752, 0.9260],
        [0.5706, 0.0780, 0.3778, 0.8355, 0.4078]])

In [148]:
torch.randint(0, 100,(3,5))

tensor([[23, 55, 60,  1, 16],
        [71, 40, 84,  0, 81],
        [32, 91, 27, 46, 70]])

In [149]:
torch.rand((3,5))

tensor([[0.7695, 0.7982, 0.0899, 0.8435, 0.7344],
        [0.3639, 0.2162, 0.1927, 0.3932, 0.2125],
        [0.1313, 0.7656, 0.1285, 0.0533, 0.6422]])

# Special Tensors

Filled with zeros

In [150]:
torch.zeros((3, 5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [151]:
torch.ones((3, 5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

# Tensors like other tensors!

In [152]:
t = torch.rand((2, 3))

In [153]:
u = torch.randn_like(t)

In [154]:
t

tensor([[0.3531, 0.9095, 0.5143],
        [0.3187, 0.6812, 0.3894]])

In [155]:
u

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

In [156]:
v = torch.ones_like(t)

In [157]:
v

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [158]:
w = torch.zeros_like(t)

In [159]:
w

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Indexing

In [160]:
u

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

First row, Second Column

In [161]:
u[0][1]

tensor(0.5839)

# Second Column

In [162]:
u[:,1]

tensor([0.5839, 3.7720])

First row

In [163]:
u[0,:]

tensor([-0.9780,  0.5839,  0.0193])

# Concatenation

In [164]:
u

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

In [165]:
t

tensor([[0.3531, 0.9095, 0.5143],
        [0.3187, 0.6812, 0.3894]])

In [166]:
torch.cat([u, t])

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454],
        [ 0.3531,  0.9095,  0.5143],
        [ 0.3187,  0.6812,  0.3894]])

Concatenate by joining the rows

In [167]:
torch.cat([u, t],dim=0)

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454],
        [ 0.3531,  0.9095,  0.5143],
        [ 0.3187,  0.6812,  0.3894]])

In [168]:
torch.cat([u,t],dim=1)

tensor([[-0.9780,  0.5839,  0.0193,  0.3531,  0.9095,  0.5143],
        [-0.4884,  3.7720,  0.1454,  0.3187,  0.6812,  0.3894]])

# Basic Arithmetic Operations

Element-wise Multiplication

In [169]:
u

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

In [170]:
v

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [171]:
t

tensor([[0.3531, 0.9095, 0.5143],
        [0.3187, 0.6812, 0.3894]])

In [172]:
u*v

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

In [173]:
u*t

tensor([[-0.3453,  0.5311,  0.0099],
        [-0.1557,  2.5694,  0.0566]])

In [174]:
0.5839*0.9095

0.5310570499999999

In [175]:
torch.mul(u,t)

tensor([[-0.3453,  0.5311,  0.0099],
        [-0.1557,  2.5694,  0.0566]])

Matrix Multiplication

In [179]:
u

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

In [180]:
t

tensor([[0.3531, 0.9095, 0.5143],
        [0.3187, 0.6812, 0.3894]])

In [181]:
torch.matmul(u,t.T) # Note that u is 2*3 and t.T is 3*2. So the result is 2*2

tensor([[0.1957, 0.0936],
        [3.3328, 2.4703]])

Getting the Abstract Value

In [194]:
s = torch.Tensor([-10,-20,30])

In [195]:
torch.abs(s) #Note that (abs) means absolute value in Riyad

tensor([10., 20., 30.])

In [196]:
u

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

In [197]:
u+1

tensor([[0.0220, 1.5839, 1.0193],
        [0.5116, 4.7720, 1.1454]])

In [198]:
t

tensor([[0.3531, 0.9095, 0.5143],
        [0.3187, 0.6812, 0.3894]])

In [199]:
u+t

tensor([[-0.6249,  1.4934,  0.5337],
        [-0.1698,  4.4532,  0.5348]])

In [200]:
0.5839 * 0.9095

0.5310570499999999

In [201]:
torch.add(u, t)

tensor([[-0.6249,  1.4934,  0.5337],
        [-0.1698,  4.4532,  0.5348]])

In [202]:
u-t

tensor([[-1.3311, -0.3255, -0.4950],
        [-0.8071,  3.0909, -0.2440]])

In [203]:
torch.sub(u,t)

tensor([[-1.3311, -0.3255, -0.4950],
        [-0.8071,  3.0909, -0.2440]])

Division (Element-wise)

In [204]:
u/t

tensor([[-2.7698,  0.6421,  0.0376],
        [-1.5327,  5.5377,  0.3734]])

In [205]:
torch.div(u, t)

tensor([[-2.7698,  0.6421,  0.0376],
        [-1.5327,  5.5377,  0.3734]])

Negation

In [206]:
u

tensor([[-0.9780,  0.5839,  0.0193],
        [-0.4884,  3.7720,  0.1454]])

In [207]:
torch.neg(u) #We use torch.ing to compare

tensor([[ 0.9780, -0.5839, -0.0193],
        [ 0.4884, -3.7720, -0.1454]])

In [208]:
-u #We use the symbol - to compare

tensor([[ 0.9780, -0.5839, -0.0193],
        [ 0.4884, -3.7720, -0.1454]])


Raising to a Power (element-wise)

In [209]:
r = torch.ones((2,3))*2

In [210]:
r

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [212]:
torch.pow(r, 5)

tensor([[32., 32., 32.],
        [32., 32., 32.]])